title: WALL-E`s Blog
subtitle: Make the world a better place.
description: null
author: SAlex
author_title: Programmer
avatar: images/walle.png
location: Beijing, China
follow: https://github.com/shiguol
email: a@a.co
language: zh-CN
timezone: null
since: 2015
url: http://shiguol.github.io
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace: null
default_category: uncategorized
category_map:
  编程: Programming
  生活: Life
tag_map: null
date_format: YYYY-MM-DD
time_format: HH:mm:ss
per_page: 10
pagination_dir: page
theme: butterfly
disqus_shortname: salexy
sitemap:
  path: sitemap.xml
deploy:
  type: git
  repository: git@github.com:shiguol/shiguol.github.io.git
  branch: master
